---
title: "Fraction of money earmarked for COVID-19 recovery could boost climate efforts"
description: |
   Global stimulus plans for economic recovery after the pandemic could easily cover climate-friendly policies, suggests a new study.
author:
  - name: Perrine Clynckemaillie
date: "`r Sys.Date()`"
#preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Fraction of money earmarked for COVID-19 recovery could boost climate efforts
  
Date: October 16, 2020
  
Source:Imperial College London
  
Summary: Global stimulus plans for economic recovery after the pandemic could easily cover climate-friendly policies, suggests a new study.
  
Global stimulus plans for economic recovery after the pandemic could easily cover climate-friendly policies, suggests new study.
Governments worldwide are planning stimulus packages to boost the economy following the disruptions caused by the COVID-19 pandemic. So far, more than $12 trillion USD have been pledged in such packages. This response is three times larger than the 2008-2009 global financial crisis recovery spending, and represents around 15 percent of global gross domestic product (GDP).
  
A new analysis published today in Science, led by researchers from Imperial College London, Climate Analytics in Berlin, and the Electric Power Research Institute in the United States, shows that if just a tenth of this money was invested each year over the next five years in climate-positive recovery plans for the global energy system, the world could be put on track to meet the goals of the Paris Agreement.
  
The Paris Agreement aims to limit the average global temperature rise this century to well below 2°C above pre-industrial temperatures and to pursue efforts to keep it at 1.5°C. This will require a reduction in the use of fossil fuels, a shift to low-carbon renewable sources of energy, such as solar and wind power, and large improvements in energy efficiency.
However, current efforts by governments worldwide are insufficient to reach the Paris Agreement goals. Instead, today's policies are leading us towards a world 3°C above pre-industrial averages. These higher temperatures will bring greater risks and more severe impacts, such as droughts, flooding and storms.
The new analysis shows that an ambitious path to a 1.5°C world is well within reach if just a fraction of COVID-19 funding is invested in a 'climate-positive' recovery, with the dual aims of stimulating the global economy and accelerating the deployment of low-carbon energy supply and energy efficiency measures. This could be achieved, for example, via direct stimulus and investments as well as via supporting policies such as incentives and rebates.
Senior author Dr Joeri Rogelj, from the Grantham Institute -- Climate Change and the Environment at Imperial, said: "Our findings show that investing in solutions to limit warming to 1.5°C is well within budget. In fact, the increase in low-carbon energy investments required over the next five years to move the world on track to meet the Paris Agreement targets is about eight times smaller than the total current COVID-19 stimulus."
First author Marina Andrijevic, from Climate Analytics and Humboldt University, said: "If just a fraction of this money was invested in climate-positive recovery plans, the world could achieve net zero carbon energy by mid-century. This is not about diverting money from COVID-19 stimulus or other low-carbon investments in industry, research and development, but providing for the win-win solution of a boosted economy that simultaneously helps our efforts to stall climate change."
Few countries have stated in full detail what they will use their recovery packages for, but immediate priorities will likely be to support healthcare systems, preserve livelihoods and stabilise employment. Beyond these, governments will be looking for investments that can foster economic recovery over the longer term.
Several reports, including a survey of over 230 experts worldwide, have shown how a green recovery can support this goal by providing both short- and long-term benefits, including job creation and lowering the investment risk of green technologies.
Dr Rogelj added: "Climate-positive recovery packages provide many benefits governments are looking for to get out of this crisis: they can boost employment and stimulate innovation, thus accelerating the development of technologies required for a global low-carbon transformation."
The team's analysis shows that a climate-positive recovery also needs a strong, near-term focus on actively avoiding a polluting recovery, such as stimulus packages that bail out fossil fuels. Investments in these sectors are poised to continue in the coming years, but there is strong evidence for redirecting this funding to a climate-positive recovery and for supporting the transition by other means, such as reskilling employees.
The analysis shows that this will be easier for some countries than others. The US and the European Union have pledged the most in post-pandemic recovery, and also need to invest the least proportionally in low-carbon energy to be on track to reach the Paris Agreement goals. Meanwhile, emerging economies like India have put forward less funding for pandemic recovery, but require proportionally more investments to provide their populations with reliable, clean and affordable energy.
Co-author Dr David McCollum, from the Electric Power Research Institute and the University of Tennessee, said: "The differing situations between developed and emerging economies in these times of crisis remind us of the need to look beyond borders and to collaborate internationally so that a climate-positive recovery benefits everyone, everywhere."
  
Story Source:
  
Materials provided by [Imperial College London](https://www.imperial.ac.uk/). Original written by Hayley Dunning.

## Article Source
[source of the article](https://www.sciencedaily.com/releases/2020/10/201015173135.html)
  
date of the publication: October 16, 2020
  
word count: 775 words

## Vocabulary

| word from the text          | synonym/definition in English                                                                                                                              | French translation          |
|-----------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|
| pre-industrial tepmperature | /                                                                                                                                                          | température préindustrielle |
| fossils fuels               | any naturally occurring carbon or hydrocarbon fuel,  such as coal, petroleum, peat, and natural gas,  formed by the decomposition of prehistoric organisms | combustibles fossiles       |
| renawable source of energy  | Renewable energy, often referred to as clean energy,  comes from natural sources or processes that are constantly replenished.                             | énergie renouvelable        |
| energy solar                | energy obtained from solar power                                                                                                                           | énergie solaire             |
| wind power                  | power produced from windmills and wind turbines                                                                                                            | énergie éolienne            |
| droughts                    | a prolonged period of scanty rainfall                                                                                                                      | sécheresses                 |
| flooding                    | the submerging of land under water, esp. due to heavy rain,  a lake or river overflowing, etc.                                                             | inondation                  |
| storms                      | blast, blizzard, cyclone, gale, gust, hurricane,  squall, tempest, tornado, whirlwind                                                                      | tempêtes                    |


## Analysis 

| researchers?                       | Dr Joeri Rogelj, from the Grantham Institute --  specialized in Climate Change and Environment at Imperial College London, Marina Andrijevic, from Climate Analytics and Humboldt University and Dr David McCollum, from the Electric Power Research Institute and the University of Tennessee                                                                                                                                   |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| published in? when (if mentioned)? | In Dailyscience and published on October 16, 2020                                                                                                                                                                                                                                                                                                                                                                                |
| general topic                      | Assessing the impact that the use of Covid-related funds could have if they were invested on global warming recovery.                                                                                                                                                                                                                                                                                                            |
| procedure/what was examined        | To show what the impact on global warming could be if we used the money made available as a result of the Covid19 crisis on global warming recovery solutions.                                                                                                                                                                                                                                                                   |
| conclusions/discovery              | The use of a part of the funds which are now given to Covid-19 related issues, to global warming recovery solutions, could improve the global environmental situation.  This could offer long-term benefits to governments as it could increase employment opportunities while stimulating innovation. This could allow one to develop new technologies and achieve low-carbon and fossil fuel bailout through short-term plans. |
| remaining questions                | /                                                                                                                                                                                                                                                                                                                                                                                                                                | 

