---
title: "Article 4 : Ice sheets on the move: How north and south poles connect"
description: | 
  the ice caps present in the 2 poles are influenced by changes in the sea level. this influence therefore helps to regulate the climate on earth, but global warming plays a role in this regulation, leading to the melting of the ice caps and therefore the rise in water levels. 
author:
  - name: Perrine Clynckemaillie
    url: {}
date: November 25, 2020
output:
  distill::distill_article:
    self_contained: false 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Ice sheets on the move: How north and south poles connect

Story Source of the article : 
  
Materials provided by [McGill University](https://www.mcgill.ca/)

## Source of the article
[source of the article](https://www.sciencedaily.com/releases/2020/11/201125114416.htm)
  
date of the publication: November 25, 2020
  
word count: 631 words  

## Vocabulary

| word from the text | Synonym/definition in English                                                                                                                            | French translation |
|--------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|
| ice sheets         | a thick layer of ice covering a large area of land for a long time,  esp. the layer that covered much of the N hemisphere during the last glacial period | calottes           |
| sea                | the mass of salt water on the earth's  surface as differentiated from the land                                                                           | mer                |
| modelling          | the act or an instance of making a model                                                                                                                 | modélisation       |
| glacial            | characterized by the presence of masses of ice                                                                                                           | glaciaire          |
| mechanisms         | a process or technique, esp. of execution                                                                                                                | mécanismes         |
| records            | an account in permanent form, esp. in writing,  preserving knowledge or information about facts or events                                                | relevés            |
| northen            | situated in or towards the north                                                                                                                         | nord               |
| hemisphere         | one half of a sphere                                                                                                                                     | hémisphère         |
| melting            | to liquefy (a solid) or (of a solid) to become liquefied,  as a result of the action of heat                                                             | font               |
| climate            | the long-term prevalent weather conditions of an area,  determined by latitude, position relative to oceans or continents, altitude, etc.                | climat             |
| cooled             | having relatively little warmth; of a rather low temperature                                                                                             | refroidissement    |
| growth             | something grown or growing                                                                                                                               | croissance         |
| warmed (to warm)   | to raise or be raised in temperature; make or become warm or warmer                                                                                      | réchauffement      |
| deglaciation       | /                                                                                                                                                        | déglaciation       |
| retreating         | to retire or withdraw                                                                                                                                    | recul              |
| sediment           | matter that settles to the bottom of a liquid                                                                                                            | sédiment           |
| polar              | situated at or near, coming from, or relating to either of  the earth's poles or the area inside the Arctic or Antarctic Circles                         | polaire            |
| shorelines         | the edge of a body of water                                                                                                                              | rivages            |
| static             | not active or moving; stationary                                                                                                                         | statique           |
| snow               | precipitation from clouds in the form of flakes of  ice crystals formed in the upper atmosphere                                                          | neige              |
| icebergs           | a large mass of ice floating in the sea, esp. a mass that  has broken off a polar glacier                                                                | icebergs           |
| intermittent       | occurring occasionally or at regular or irregular intervals; periodic                                                                                    | intermittentes     |
| reconciled         | to make (oneself or another) no longer opposed;  cause to acquiesce in something unpleasant                                                              | reconcilliés       |
| interconnected     | /                                                                                                                                                        | interconnexion     |

## Analysis

### Researchers?

*  	Gomez, N., Weber, M.E., Clark, P.U. et al. Antarctic ice dynamics amplified by Northern Hemisphere sea-level forcing

### published in ? when (if mentioned)?

*  published in Dayliscience
*  on November 25, 2020

### general topic

*  The movement of ice sheets in the two hemispheres 
*  Those movements are induced by sea water level changes

### procedure/what was examined

*  Global warming leads to the water level change of seas and oceans *  The water level influences ice sheets in both hemispheres 
*  Ice sheets of the two Poles influence each other

### conlusions/discovery

*  There is an interconnection in the earth system 
*  This interconnection translates into changes in other parts of the planet 
*  One can see a withdrawal of ice sheets following global warming

### remainig question : /
