---
title: "Article 5 :Arctic permafrost releases more CO2 than once
believed"
description: |
  A short description of the post.
author:
  - name: Perrine Clynckemaillie
    url: {}
date: 03-12-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source of the article
[source of the article](:	https://www.sciencedaily.com/releases/2021/02/210209113807.htm)

date of the publication: February 9, 2021
  
word count: 652 words

## Vocabulary

| word from the text | synonym/definition in English                                                                                                                                                                                                                                                                                                                                                | French translation   |
|--------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------|
| greater            | Great : relatively large in size or extent; big                                                                                                                                                                                                                                                                                                                              | plus grand           |
| organic matter     | Organic : constitutional in the structure of something; fundamental; integral Matter : that which makes up something, esp. a physical object; material                                                                                                                                                                                                                       | matière organique    |
| tightly            | Adv,adj =tight :held, made, fixed, or closed firmly and securely                                                                                                                                                                                                                                                                                                             | bien serré           |
| iron               | a malleable ductile silvery-white ferromagnetic metallic element occurring  principally in haematite and magnetite. It is widely used for structural and  engineering purposes. See also steel, cast iron, wrought iron, pig iron.  Symbol: Fe; atomic no.: 26; atomic wt.: 55.847; valency: 2,3,4, or 6;  relative density: 7.874; melting pt.: 1538°C; boiling pt.: 2862°C | fer                  |
| anthropogenic      | Adj,n = the study of the origins of man                                                                                                                                                                                                                                                                                                                                      | anthropique          |
| melts (to melt)    | to liquefy (a solid) or (of a solid) to become liquefied, as a result of  the action of heat                                                                                                                                                                                                                                                                                 | fond                 |
| soil               | the top layer of the land surface of the earth that is composed of disintegrated  rock particles, humus, water, and air                                                                                                                                                                                                                                                      | sol                  |
| thaws (to thaw)    | to melt or cause to melt from a solid frozen state                                                                                                                                                                                                                                                                                                                           | dégèle (dégeler)     |
| greenhouse         | relating to or contributing to the greenhouse effect                                                                                                                                                                                                                                                                                                                         | serre                |
| trapping (to trap) | to catch, take, or pen in or as if in a trap; entrap                                                                                                                                                                                                                                                                                                                         | piégé (piège)        |
| bonds              | something that binds,fastens, or holds together, such as a chain or rope                                                                                                                                                                                                                                                                                                     | liaisons             |
| drop               | the act	or an instance of falling; descent                                                                                                                                                                                                                                                                                                                                    | baisse               |
| bog                | wet spongy ground consisting of decomposing vegetation, which ultimately forms peat                                                                                                                                                                                                                                                                                          | tourbière            |
| worldwide          | applying or extending throughout the world; universal                                                                                                                                                                                                                                                                                                                        | à l'échelle mondiale |
| whether            | used to introduce an indirect question or a clause after a verb expressing or  implying doubt or choice in order to indicate two or more alternatives, the second  or last of which is introduced by or or or whether                                                                                                                                                        | si                   |
| countlesse         | innumerable; myriad                                                                                                                                                                                                                                                                                                                                                          | d'innombrables       |

### Researchers?

Monique S. Patzner, Carsten W. Mueller, Miroslava Malusova, Moritz Baur, Verena Nikeleit, Thomas Scholten, Carmen Hoeschen, James M. Byrne, Thomas Borch, Andreas Kappler, Casey Bryce

### Published	in? when (if mentioned)?

  - In	dailyscience
  - Published	on February 9, 2021
  
### General	topic :

  - Topic	around CO2, iron and	permafrost
  
### Procedure/what was examined :
	
  - bacteria neutralise	the	carbon capacity -> release	of	large	amounts of CO2
  - when the ice melts, the water becomes water -> Oxygen level decreases	and	Iron becomes unstable

### Conclusions/	discovery :
/
